### ISSUE TITLE
[Task] Support multiple status pages

### ISSUE THREAD

**Issue by yangshuDBA** [apache/hertzbeat#1732]
### Description

当前状态监控界面只有一个，如果服务放的过多需要鼠标上下滚动很久才能看完。
建议增加多个状态界面，实现一个业务系统对应一个状态页面。
serviceIP:1157/status
多状态页参考如下
![image](https://github.com/dromara/hertzbeat/assets/112070510/d57123e2-5a88-4621-978f-eff8ddc191f5)
组件编辑参考如下
![image](https://github.com/dromara/hertzbeat/assets/112070510/dfedc0d1-3b95-4d82-bd3e-80638efd37b7)
事件发布页参考如下
![image](https://github.com/dromara/hertzbeat/assets/112070510/821eb20e-11c9-47e0-9b00-5c3ac07ecc59)

### Task List

任务一：实现状态页面自定义地址
任务二：实现自定义状态页面的组件管理
任务三：实现自定义状态页面的事件管理

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Description

There is currently only one status monitoring interface. If there are too many services, it will take a long time to scroll up and down with the mouse to see them all.
It is recommended to add multiple status interfaces so that one business system corresponds to one status page.
serviceIP:1157/status
Multi-status page reference is as follows
![image](https://github.com/dromara/hertzbeat/assets/112070510/d57123e2-5a88-4621-978f-eff8ddc191f5)
Component editing reference is as follows
![image](https://github.com/dromara/hertzbeat/assets/112070510/dfedc0d1-3b95-4d82-bd3e-80638efd37b7)
The event release page is as follows
![image](https://github.com/dromara/hertzbeat/assets/112070510/821eb20e-11c9-47e0-9b00-5c3ac07ecc59)



### Task List

Task 1: Implement a custom address for the status page
Task 2: Implement component management of custom status pages
Task 3: Implement event management of custom status pages
