### ISSUE TITLE
[Task] <add team page in website>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#1767]
### Description

add team page in website  https://github.com/apache/hertzbeat/tree/master/home
- add our memtors detail
- add our ppmc detail
- add out contributors detail 

refer https://streampark.apache.org/team

**Comment by alpha951** [comment]
I would love to work on this. Could you please assign this issue to me.

**Comment by tomsun28** [comment]
hi, welcome. 💗
The mentors and ppmc information are here. https://github.com/apache/hertzbeat/issues/1634 
<img width="609" alt="image" src="https://github.com/apache/hertzbeat/assets/24788200/9c3b0e4e-e946-4671-8d83-1eac25156c6b">
The all contributors information in readme https://github.com/apache/hertzbeat?tab=readme-ov-file#-contributors , suggest copy directly the contributors wall in the team page.

**Comment by alpha951** [comment]
Hey, I need little help with this. Do I suppose to implement this from scratch like here https://github.com/apache/hertzbeat/tree/master/home/src/pages  create a team.jsx etc. Or since we are using docusaurus library, so creating a markdown will do the job ? Or you can share the code link of this page https://streampark.apache.org/team/

**Comment by alpha951** [comment]
Hey @tomsun28 , I've created this draft PR https://github.com/apache/hertzbeat/pull/1800 .
Please suggest changes.
